backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
collections: 
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    media_folder: "public/images"
    public_folder: "images"
    create: false
    slug: "{{title}}"
    fields: 
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Featured Image", name: "image", widget: "image"}
     - {label: "Body", name: "body", widget: "markdown"}
  - name: "author"
    label: "Author"
    folder: "_authors"
    create: true
    slug: "{{last_name}}_{{first_name}}_{{day}}{{hour}}{{minute}}"
    identifier_field: "last_name"
    media_folder: "public/author_images"
    public_folder: "author_images"
    fields: 
     - {label: "Date Created", name: "date", widget: "date", date_format: "DD-MM-YYYY", required: true}
     - {label: "First Name", name: "first_name", widget: "string", required: true}
     - {label: "Last Name", name: "last_name", widget: "string", required: true}
     - {label: "Website URL", name: "url", widget: "string", required: false}
     - {label: "Twitter Handle", name: "twitter", widget: "string", required: false}
     - {label: "Instagram Handle", name: "instagram", widget: "string", required: false}
     - {label: "Author's Image", name: "image", widget: "image", required: true}
     - {label: "Body", name: "body", widget: "markdown", required: true}