backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: public/images
public_folder: "images"
collections: 
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: false
    slug: {{slug}}
    fields: 
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Featured Image", name: "image", widget: "image"}
     - {label: "Body", name: "body", widget: "markdown"}